<div class="search-bar ">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="DIGITE ALGO...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>

<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="<?php echo $systemConfig::SYSTEM_ROOT; ?>/inicio"><?php echo $systemConfig::SYSTEM_NAME_FORMATED; ?></a>
            <div class="btn-group user-helper-dropdown m-t-10" style='box-shadow:none'>
                <a href="javascript:void(0);"  aria-expanded="true" aria-haspopup="true" data-toggle="dropdown" class="pull-right ">  
                    <img  class="topbar-foto" src="<?php echo $systemConfig::URL_PUBLIC; ?>/all/perfil/exemplo.jpg" width="48" height="48" alt="User"></a>
                <?php include "module/sistema/view/layout/3-1-topbar-user.phtml"; ?>
            </div>
        </div>
        <?php include "module/sistema/view/layout/3-2-topbar-options.phtml"; ?>
    </div>
</nav>
<!-- #Top Bar -->