<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <h2>INÍCIO</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body">
                        <div class="row">
                            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
                                <div class="texto">
                                    <h3>VIVALDO & SOUZA</h3>
                                    <p>Transporte e Logistica</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

