<?php

use core\helper\SessionHelper;

$perfil = SessionHelper::getSessionValue('segPerfil');

// $permisaoAcesso = new core\helper\PermissaoAcessoHelper();
// $arrayPermissoes = SessionHelper::getSessionValue('segPermissoes');

//1	LÍDER
//2	DONO DO PRODUTO
//3	DESENVOLVEDOR
//4	TESTE
//5	ADMINISTRADOR DE DAD


// if ($perfil == 1 || $perfil == 2 || $perfil == 6) {

//     $arrayPermissoes['produto']['inicio'] = 1;
//     $arrayPermissoes['ticket']['movimentacaoticket'] = 1;
//     $arrayPermissoes['ocorrencia']['inicio'] = 1;
//     $arrayPermissoes['imprimir']['inicio'] = 1;
//     $arrayPermissoes['relatorio']['inicio'] = 1;
//     $arrayPermissoes['ticket']['gerenciarticketdoproduto'] = 1;
//     $arrayPermissoes['sprint']['gerenciarsprintdoproduto'] = 1;
//     $arrayPermissoes['usuario']['gerenciartimedoproduto'] = 1;
// } else if ($perfil == 4) {

//     $arrayPermissoes['produto']['inicio'] = 1;
//     $arrayPermissoes['ticket']['movimentacaoticket'] = 1;
//     $arrayPermissoes['relatorio']['inicio'] = 1;
//     $arrayPermissoes['ticket']['gerenciarticketdoproduto'] = 1;
//     $arrayPermissoes['sprint']['gerenciarsprintdoproduto'] = 1;
// } else {
//     $arrayPermissoes['produto']['inicio'] = 1;
//     $arrayPermissoes['ticket']['movimentacaoticket'] = 1;
//     $arrayPermissoes['ticket']['gerenciarticketdoproduto'] = 1;
//     $arrayPermissoes['menu']['subtipodespesa'] = 1;
//     $arrayPermissoes['subtipodespesa']['inicio'] = 1;
//     $arrayPermissoes['tipodespesa']['inicio'] = 1;
//     $arrayPermissoes['exercicio']['inicio'] = 1;
//     $arrayPermissoes['unidademedida']['inicio'] = 1;

//     $arrayPermissoes['perfil']['meusdados'] = 1;
//     $arrayPermissoes['perfil']['alterarSenha'] = 1;
// }
?>

<section>
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MENU</li>

                <li class="<?php activeMenu('inicio', $menu) ?> inicio">
                    <a href="<?php echo $systemConfig::SYSTEM_ROOT . '/inicio'; ?>">
                        <i class="material-icons bg-grey">home</i>
                        <span>Início</span>
                    </a>
                </li>


                <li class="">
                    <a href="javascript:void(5);" class="menu-toggle <?php toggledMenu(array('perfil'), $menu); ?>">
                        <i class="material-icons bg-grey">format_list_bulleted</i>
                        <span>Logistica</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="<?php activeMenu('perfil', $menu) ?>">
                            <a href="<?php echo $systemConfig::SYSTEM_ROOT . '/novoRecebimento/inicio' ?>" class="">
                                <span class="submenuespecial">Novo Recebimento</span>
                            </a>
                        </li>
                    </ul>
                </li>



                <li class="">
                    <a href="javascript:void(0);" class="menu-toggle <?php toggledMenu(array('perfil'), $menu); ?>">
                        <i class="material-icons bg-grey">format_list_bulleted</i>
                        <span>Meu Perfil</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="<?php activeMenu('perfil', $menu) ?>">
                            <a href="<?php echo $systemConfig::SYSTEM_ROOT . '/perfil/meusdados' ?>" class="">
                                <span class="submenuespecial">Meus dados</span>
                            </a>
                        </li>
                        <li class="<?php activeMenu('perfil', $menu) ?>">
                            <a href="<?php echo $systemConfig::SYSTEM_ROOT . '/perfil/alterarSenha' ?>" class="">
                                <span class="submenuespecial">Alterar Senha</span>
                            </a>
                        </li>
                        <li class="<?php activeMenu('logout', $menu) ?>">
                            <a href="<?php echo $systemConfig::SYSTEM_ROOT . '/logout' ?>" class="">
                                <span class="submenuespecial">Sair do sistema</span>
                            </a>
                        </li>
                    </ul>
                </li>


        </div>
    </aside>
</section>


<div class="m-l-15 m-r-15 m-b-15">
    <ol class="breadcrumb system">
        <li><a href="javascript:void(0);">Início</a></li>
        <?php foreach ($textBreadcrumb as $tbc) { ?>
        <li><a href="javascript:void(0);"><?php echo $tbc; ?></a></li>
        <?php } ?>
        <!--<li class="active">Dados</li>-->
    </ol>
</div>
<!-- # Breadcrumb -->

<input type="hidden" id="system-url" value="<?php echo $systemConfig::SYSTEM_ROOT ?>">