
<style>

    section.content {
        margin: 95px 15px 0 15px!important;
    }
</style>


<!-- Conteúdo -->

<section class="content">

    <div class="container">
        <div class="row clearfix">
            <!-- #INICIO teste -->
            <!-- Column -->
            <div class="col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2><?php echo $pageTitle; ?></h2>
                    </div>
                    <div class="body clearfix ">
                        <form role="form" action="selecaoPerfil" name="frmSelecionarPerfil" id="frmSelecionarPerfil" method="post">

                            <h4 class="card-title m-t-10 ">Olá, <strong><?php echo $usuNome; ?></strong></h4>

                            <div class="row  col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                                <h5>Você possui <strong>mais de um perfil de acesso</strong> e deverá escolher apenas um por vez para continuar o acesso.
                            </div>  


                            <div class=" col-md-offset-4    col-md-4 col-sm-12 col-xs-12  ">
                                <label for="PERFILACESSO" class="m-t-5" >Perfil de acesso:</label>
                                <div class="form-group m-b-10">
                                    <div class="form-line ">
                                        <select id="PERFILACESSO" name="PERFILACESSO"  class="selectpicker form-control select" data-live-search="false" style="display: none;" >
                                            <?php $this->makeOptions($perfis, NULL, NULL, TRUE); ?>
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class=" col-md-offset-5    col-md-4 col-sm-12 col-xs-12  "> 
                                <div class=" form-group">
                                    <a  class="btn bg-green waves-effect border-radius-5 btn-salvar" form-submit>
                                        <i class="material-icons">save</i>
                                        <span class="">Escolher</span>
                                    </a>
                                </div>
                            </div>
                            
                            <div class=" row col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center justify-content-md-center">      
                                <br> Lembrando que o perfil pode ser alterado a qualquer momento através da função "Perfil de acesso" 
                                <br> localizado na barra azul superior do sistema.<h5>
                            </div>
                        </form>
                    </div>
                    <br>
                </div>
            </div>

        </div>
    </div>

</section>
<!-- #FIM Conteúdo -->