<?php
use config\SystemConfig;
use core\helper\SessionHelper;
?>
<link href="<?php echo SystemConfig::URL_CORE_STYLEGUIDE ?>/css/templates/template-1.css" rel="stylesheet">
<div class="row container template-1-container">
    <div class="row template-1-conteudo">
        <div class="m-l-20">
            <img src="<?php echo SystemConfig::LOGO_GOV_IMG ?>" class="pull-left template-1-logo-gov">
        </div>
        <div style="bottom: 10px;" class="col-lg-10 col-sm-10 col-md-10 col-xs-10">
            <h3 style="font-size: 20px;">Governo do Estado da Bahia<br>
                Secretaria da Educação<br>
                Assessoria de Planejamento e Gestão - APG</h3>
        </div>
        <?php if (!empty(SystemConfig::LOGO_APP_IMG)) { ?>
            <div class="col-lg-2 pull-right">
                <img src="<?php echo SystemConfig::LOGO_APP_IMG ?>" class="pull-left template-1-logo-app">
            </div>
        <?php } ?>
    </div>
    <div class="col-lg-12 align-center m-t--10 m-b-40">
        <b style="font-size: 15px; text-transform: uppercase;"><?php echo $pageTitle; ?></b>
    </div>
    <?php include($this->template); ?>
    <div class="row template-1-rodape">
        <hr class="m-b-10">
        <small>
            <?php
            if (isset($templateRegistros)) {
            ?>
                <span>Total de Registro(s): <strong><?php echo $templateRegistros; ?></strong></span>
                <br>
            <?php } ?>
            <span>
                Emitido por <strong><?php echo SessionHelper::getSessionValue("usuNome"); ?></strong>
            </span>
            <span>
                em <strong><?php echo date('d/m/Y'); ?></strong>
                às <strong><?php echo date('H:i:s'); ?></strong>
            </span>
        </small>
    </div>
</div>
<div class="bt-print-float">
    <div class="form-group botao m-t-20">
        <div class="">
            <a class="btn bg-grey waves-effect" href="javascript:window.print()">
                <i class="material-icons">print</i>
                <span class="m-r-10">Imprimir</span>
            </a>
            <a href="javascript:window.close()" class="btn bg-red waves-effect ">
                <i class="material-icons">close</i>
                <span class="m-r-10">Fechar</span>
            </a>
        </div>
    </div>
</div>