<?php

use config\SystemConfig;
use core\helper\FormatHelper;

// use module\SGTVES\consts\TipoUsuarioConsts;
?>


<style>
    .teste{
        border: solid 1px;
        border-color: #cccccc;
        padding-top: 20px;
        width: 593px;
        margin-left: 19px;
        margin-bottom: 30px;
    }
</style>

<section class="content pg-adicionar form">
    <div class="container-fluid">
        <div class="block-header">
            <h2>
                <?php echo $pageTitle; ?>
            </h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body">

                        <h3>Upload de Nota Fiscal</h3>
                        <div class="row">
                            <div class="col-md-12  col-sm-4 col-xs-12 teste">
                                <div class="form-group">
                                    <form id='formulario' action="upload" method="POST" enctype="multipart/form-data">
                                        <div class="form-group">
                                            <input class='btn btn-outline-light btn-fw' type="file"
                                                   name="file[]"
                                                   id="upload" multiple="multiple">
                                        </div>
<!--                                        <button id="btnSave"-->
<!--                                                class="file-upload-browse btn bg-green btn-fw"-->
<!--                                                type="submit">Salvar-->
<!--                                        </button>-->

                                        <div class="form-group">
                                            <div class="">
                                                <a class="btn bg-green waves-effect border-radius-5 btn-salvar" form-submit>
                                                    <i class="material-icons">save</i>
                                                    <span class="m-r-10">Salvar</span>
                                                </a>
                                                <a href="<?php echo $systemConfig::SYSTEM_ROOT ?>/novoRecebimento/inicio"
                                                   class="btn bg-orange waves-effect border-radius-5">
                                                    <i class="material-icons">reply</i>
                                                    <span class="m-r-10">Voltar</span>
                                                </a>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</section>