<?php

use config\SystemConfig;
?>
<!-- Custom Css -->
<link href="<?php echo $systemConfig::URL_CORE_CSS ?>/style.css" rel="stylesheet">

<!-- login -->
<link href="<?php echo $systemConfig::URL_PUBLIC ?>/sistema/login/css/login.css" rel="stylesheet" />

</head>

<body class="login-page clearfix">
    <div class="login-box clearfix">
        <div class="card">
            <div class="header">
                <div class="logo">
                    <a><?php echo $systemConfig::SYSTEM_NAME_FORMATED; ?></a>
                    <small><?php echo $systemConfig::SYSTEM_DESCRICAO; ?> </small>
                </div>
            </div>
            <div class="body clearfix">
                <div class='col-md-12'>
                    <form  id="frmLogin" name="frmLogin" method="post" action="<?php echo $systemConfig::SYSTEM_ROOT; ?>/login">
                        <h4>Faça login para iniciar sua sessão</h4>
                        <div class="form-group form-float m-t-20 ">
                            <div class="form-line">
                                <input type="text" id="usuario" name="usuario"  class="form-control" maxlength="30">
                                <label class="form-label label-focused-fix">Usuário</label>
                            </div>
                        </div>

                        <div class="form-group form-float ">
                            <div class="form-line">
                                <input type="password" id="senha" name="senha" maxlength="32" class="form-control">
                                <label class="form-label label-focused-fix">Senha</label>
                            </div>
                        </div>

                        <div class="col-xs-12 col-lg-12 col-sm-12 p-l-10">
                            <div class="form-group">
                                <div class="g-recaptcha" data-sitekey="<?php echo SystemConfig::RECAPTCHA_PUBLIC_KEY; ?>" data-callback="verifyRecaptchaCallback" data-expired-callback="expiredRecaptchaCallback"></div>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="row p-t-45">
                            <div class="col-xs-12">
                                <button class="btn btn-blocks bg-primary waves-effect btn-block" type="submit">ENTRAR</button>
                            </div>
                        </div>
                    </form>
                </div> <!-- md-6 -->
            </div>
            <hr style='margin:0px'/>
            <div class="p-t-10 p-b-15">                
                <div class=" t-center">
                    <a href="#" class="col-red">Esqueci minha senha</a>
                </div>
            </div>
        </div>
    </div>

