<?php

use module\sised\consts\PerfilConsts;
use module\sised\consts\StatusConsts;
?>
<style type="text/css">
    [disabled]{
        cursor: no-drop !important;
    }
</style>  

<!-- Conteúdo -->
<section class="content pg-adicionar">
    <div class="container-fluid">
        <div class="block-header">
            <h2>
                <?php echo $pageTitle; ?>
            </h2>
        </div>
        <div class="row clearfix">
            <!-- #INICIO teste -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    <div class="body clearfix">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <!-- CONTEUDO -->
                            <form role="form" action="adicionar" name="frmAdicionar" id="frmAdicionar" method="post">
                                <input type="hidden" name="ID_FUNCIONARIO_USUARIO" value="<?php echo $objFuncionarioVO->getId(); ?>">
                                <div class="row">
                                    <div class="col-md-12 col-sm-4 col-xs-10">                                    
                                        <label for="nome" >Nome do Funcionário:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="nome" class="form-control" id="nome"  maxlength="100" value="<?php echo $objFuncionarioVO->getNome(); ?>" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-4 col-xs-10">                                         
                                        <label for="matricula" >Matrícula:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="matricula" class="form-control" id="matricula"  maxlength="5" value="<?php echo $objFuncionarioVO->getMatricula(); ?>" >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-4 col-xs-10">                                         
                                        <label for="passoword" >Senha:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="passoword" class="form-control" id="passoword"  maxlength="20" value="<?php echo $objFuncionarioVO->getSenha(); ?>" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-4 col-xs-10">                                        
                                        <label for="CPF" >cpf:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="cpf" class="form-control" id="cpf"  maxlength="14" value="<?php echo $objFuncionarioVO->getCpf(); ?>" >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6  col-sm-4 col-xs-10">  
                                        <label for="id_setor" >Setor:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <select id="id_setor" name="id_setor"  class="selectpicker form-control select" data-live-search="true" style="display: none;">                                            
                                                    <?php $this->makeOptions($arraySetor, 'Id', 'Nome', TRUE, $objFuncionarioVO->getIdSetor()->getId()); ?>
                                                </select> 
                                            </div>
                                        </div>
                                    </div>
                                </div> 
                                <div class="row">
                                    <div class="col-md-6  col-sm-4 col-xs-10">                                       
                                        <label for="telefone" >Telefone:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="telefone" class="form-control" id="telefone"  maxlength="15" value="<?php echo $objFuncionarioVO->getTelefone(); ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6  col-sm-4 col-xs-10">                                      
                                        <label  for="celular" >Celular:</label>
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input  type="text" name="celular" class="form-control" id="celular"   maxlength="16" value="<?php echo $objFuncionarioVO->getCelular(); ?>" >
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8  col-sm-12 col-xs-12">                                        
                                        <label for="tipo_usuario" >Tipo de Usuário:</label>
                                        <div class="form-group">
                                            <div class="form-group">
                                                <input name="tipo_usuario" type="radio" id="administrador" class="with-gap radio-col-blue" value="A" <?php echo $objFuncionarioVO->getTipoUsuario() == "A" ? 'checked' : ''; ?>/>
                                                <label for="administrador" class="no-red">Administrador</label>
                                                <br>
                                                <input name="tipo_usuario" type="radio" id="USUARIO" class="with-gap radio-col-blue" value="U" <?php echo $objFuncionarioVO->getTipoUsuario() == "U" ? 'checked' : ''; ?>/>
                                                <label for="usuario" class="no-red">Usuário</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                        <a  class="btn bg-green waves-effect border-radius-5 btn-salvar" form-submit>
                                            <i class="material-icons">save</i>
                                            <span class="m-r-10">Salvar</span>
                                        </a>                                    
                                        <a  href="<?php echo $systemConfig::SYSTEM_ROOT ?>/funcionario" class="btn bg-orange waves-effect border-radius-5">
                                            <i class="material-icons">reply</i>
                                            <span class="m-r-10">Voltar</span>
                                        </a>

                                    </div>
                                </div>
                            </form>
                            <!--CONTEUDO-->
                        </div><!-- col-md-6 -->
                    </div><!-- body -->
                </div>
            </div>
            <!-- #FIM teste -->
        </div>
</section>
<!-- #FIM Conteúdo -->
