<?php

use config\SystemConfig;
?>
<!-- Custom Css -->
<link href="<?php echo $systemConfig::URL_CORE_CSS ?>/style.css" rel="stylesheet">

<!-- login -->
<!--<link href="<?php echo $systemConfig::URL_PUBLIC ?>/sistema/login/css/login.css" rel="stylesheet" />-->

</head>

<body class="login-page" >

    <div class="login-box clearfix container">       
        
        
      
        
                    
         <div class="card">
            <div class="header">
                
                <div class="logo">
                    <a><?php echo $systemConfig::SYSTEM_NAME_FORMATED; ?></a>
                    <small><?php echo $systemConfig::SYSTEM_DESCRICAO; ?> </small>
                </div>
                
                <div class="logo-img">
                    <img src="<?php echo $systemConfig::URL_PUBLIC ?>/all/logo/logo-dark.png" alt="SEC" />
                </div>

                
                <div class="clear"></div>
            </div>
            <div class="body clearfix">
                <h4 style="text-align: center;    font-size: 15px;    text-transform: uppercase;    margin: 0px 0px 2px 0px;">Cadastrar</h4>
                  <div class="box-info" style="padding: 15px 0px;font-size: 14px;color: #666;">
                    <p style="text-align: left">Caros Professores,
                    O Governo do Estado da Bahia, buscando implementar o Sistema de Apoio à Prática Pedagógica, solicita o preenchimento das informações com a máxima atenção. Através deste cadastro, buscamos contemplá-los com o acesso ao sistema.</p>
                </div>
                <form  id="frmLogin" name="frmLogin" method="post" action="<?php echo $systemConfig::SYSTEM_ROOT; ?>/cadastro">                    


                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="form-group form-float ">
                                <div class="form-line">
                                    <input type="text" id="CPF" name="CPF"  class="form-control" maxlength="14">
                                    <label for="CPF" class="form-label label-focused-fix" >CPF:</label>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group form-float ">
                                <div class="form-line">
                                    <input type="text" id="EMAIL" name="EMAIL"  class="form-control" maxlength="255">
                                    <label for="EMAIL" class="form-label label-focused-fix">E-mail:</label>
                                </div>
                            </div>
                        </div>
                    </div><!-- row -->

                    <div class="row"> 
                        <div class="col-md-6">                    
                            <div class="form-group form-float ">
                                <div class="form-line">
                                    <input type="text" id="CADASTRO" name="CADASTRO"  class="form-control" maxlength="9">
                                    <label for="CADASTRO" class="form-label label-focused-fix">Cadastro:</label>
                                </div>
                            </div>
                        </div>

                       <div class="col-md-6">                    
                            <div class="form-group form-float ">
                                <div class="form-line">
                                    <input type="text" id="DATA_NASCIMENTO" name="DATA_NASCIMENTO"  class="form-control" maxlength="10">
                                    <label for="DATA_NASCIMENTO" class="form-label label-focused-fix">Data de Nascimento:</label>
                                </div>
                            </div>
                       </div>
                   </div>

                <div class="row"> 
                    <div class="col-md-6">                    
                            
                    <div class="form-group form-float ">
                        <div class="form-line">
                            <input type="password" id="SENHA" name="SENHA" class="form-control" maxlength="10">
                            <label for="SENHA" class="form-label label-focused-fix">Senha:</label>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">                    
                    <div class="form-group form-float ">
                        <div class="form-line">
                            <input type="password" id="CONFIRMARSENHA" name="CONFIRMARSENHA" class="form-control" maxlength="10">
                            <label for="CONFIRMARSENHA" class="form-label label-focused-fix">Confirmar Senha:</label>
                        </div>
                    </div>
                    </div>
               </div>

                    <div class="col-xs-12 col-lg-12  col-lg-offset-3 col-sm-12 p-l-10">
                        <div class="form-group">
                            <div class="g-recaptcha" data-sitekey="<?php echo SystemConfig::RECAPTCHA_PUBLIC_KEY; ?>" data-callback="verifyRecaptchaCallback" data-expired-callback="expiredRecaptchaCallback"></div>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                    <div class="row p-t-45">
                        <div class="col-md-6 col-md-offset-3">
                        <div class="col-md-6" style="padding: 0px;">
                            <button class="btn btn-blocks bg-primary waves-effect btn-block" type="submit" style="border-radius:3px 0px 0px 3px !important;">Cadastrar</button>
                        </div>
                         <div class="col-md-6" style="padding: 0px;">
                             <a href="/login" class="btn btn-blocks bg-orange waves-effect btn-block" type="back" style="border-radius: 0px 3px 3px 0px !important">Voltar</a>
                        </div>
                        </div>
                    </div>
                    <div class="row m-t-25 m-b--20">
                        <div class="col-xs-12 t-center">
                            <a href="/recuperarSenha" class="col-red">Esqueci minha senha</a>
                        </div>
                    </div><br>
                </form>
            </div>
        </div>
    </div>

